language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

install: source build_tools/travis/install.sh

script:
  - if [ ${COVERAGE} == "true" ];
    then nosetests --with-coverage --with-timer --timer-top-n 20; else
    nosetests --with-timer --timer-top-n 20;
    fi

after_success:
  - if [ ${COVERAGE} == "true" ]; then
    pip install codecov;
    codecov;
    fi
