language: python

python:
  - 3.4
  - 3.5

notifications:
    email: false

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=skopt
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0" CYTHON_VERSION="0.21"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.10.1" SCIPY_VERSION="0.16.0" CYTHON_VERSION="0.23.4"

install: source ci_scripts/install.sh

script:
  nosetests
